import type { HomeBanner } from '@/features/home/home.types';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { ImageBackground, Pressable, StyleSheet, Text, View } from 'react-native';

export function Banner({ banner }: { banner: HomeBanner }) {
  return <View style={styles.wrapper}><ImageBackground source={{ uri: banner.imageUrl }} imageStyle={styles.image} style={styles.banner}><View style={styles.copy}>{banner.discountPercent != null && <Text style={styles.discount}>ƯU ĐÃI {banner.discountPercent}%</Text>}<Text numberOfLines={2} style={styles.title}>{banner.title}</Text><Text numberOfLines={2} style={styles.caption}>{banner.subtitle}</Text><Pressable onPress={() => router.push('/booking/select-service')} style={styles.button}><Text style={styles.buttonText}>{banner.buttonText.toUpperCase()}</Text><Ionicons name="arrow-forward" size={14} color="#FFF" /></Pressable></View></ImageBackground><View style={styles.dots}><View style={[styles.dot, styles.active]} /><View style={styles.dot} /><View style={styles.dot} /></View></View>;
}
const styles = StyleSheet.create({ wrapper: { marginHorizontal: 16, marginTop: 10 }, banner: { height: 190, overflow: 'hidden', justifyContent: 'center' }, image: { borderRadius: 17 }, copy: { width: '58%', paddingLeft: 19 }, discount: { color: '#A83E5E', fontSize: 9, fontWeight: '900', letterSpacing: .8, marginBottom: 5 }, title: { color: '#794151', fontSize: 20, lineHeight: 23, fontWeight: '800' }, caption: { color: '#866D74', fontSize: 10, lineHeight: 14, marginTop: 5 }, button: { marginTop: 10, backgroundColor: '#C95277', borderRadius: 18, paddingVertical: 9, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 7 }, buttonText: { color: '#FFF', fontSize: 10, fontWeight: '700' }, dots: { position: 'absolute', right: 17, bottom: 10, flexDirection: 'row', gap: 6 }, dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: 'rgba(255,255,255,.8)' }, active: { width: 8, backgroundColor: '#CD5779' } });
