import type { FeaturedArtist } from '@/features/home/home.types';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

export function FeaturedArtists({ artists }: { artists: FeaturedArtist[] }) {
  if (artists.length === 0) return null;
  return <View><View style={styles.header}><View><Text style={styles.title}>Nghệ nhân nổi bật</Text><Text style={styles.subtitle}>Tay nghề tinh hoa chăm chút từng chi tiết</Text></View><Pressable onPress={() => router.push('/booking/select-staff')}><Text style={styles.seeAll}>Tất cả</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.list}>{artists.map((artist) => <View key={artist.id} style={styles.card}>{artist.expert && <View style={styles.expertBadge}><Text style={styles.expertText}>EXPERT</Text></View>}<View><Image source={{ uri: artist.avatarUrl }} style={styles.image} /><View style={styles.rating}><Ionicons name="star" size={12} color="#E5A62B" /><Text style={styles.ratingText}>{Number(artist.rating).toFixed(1)}</Text></View></View><Text style={styles.name}>{artist.name}</Text><Text style={styles.experience}>{artist.experienceYears} năm kinh nghiệm</Text><Text numberOfLines={1} style={styles.specialty}>{artist.specialty}</Text><Pressable onPress={() => router.push({ pathname: '/booking/select-service', params: { staffId: artist.id } })} style={({ pressed }) => [styles.button, pressed && styles.buttonPressed]}><Text style={styles.buttonText}>Chọn thợ</Text></Pressable></View>)}</ScrollView></View>;
}
const styles = StyleSheet.create({ header: { paddingHorizontal: 16, marginTop: 20, marginBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { color: '#2F2529', fontSize: 19, fontWeight: '800' }, subtitle: { color: '#A45B70', fontSize: 10, marginTop: 3 }, seeAll: { color: '#B74566', fontSize: 12, fontWeight: '600' }, list: { paddingHorizontal: 16, gap: 12 }, card: { width: 166, padding: 13, borderRadius: 28, backgroundColor: '#FFF', alignItems: 'center', borderWidth: 1, borderColor: '#F7EAED' }, image: { width: 132, height: 76, borderRadius: 38 }, rating: { position: 'absolute', right: -2, bottom: -6, backgroundColor: '#FFF', borderRadius: 12, paddingHorizontal: 7, paddingVertical: 4, flexDirection: 'row', alignItems: 'center', gap: 2 }, ratingText: { color: '#33292C', fontSize: 11, fontWeight: '700' }, expertBadge: { position: 'absolute', zIndex: 2, right: 4, top: 7, backgroundColor: '#F6DFB9', borderRadius: 9, paddingHorizontal: 6, paddingVertical: 3 }, expertText: { color: '#946821', fontSize: 7, fontWeight: '800' }, name: { color: '#342A2D', fontSize: 16, fontWeight: '800', marginTop: 14 }, experience: { color: '#B04D69', fontSize: 10, marginTop: 3 }, specialty: { color: '#79696E', fontSize: 10, marginTop: 7 }, button: { width: '100%', backgroundColor: '#FCE5EC', borderRadius: 18, paddingVertical: 8, alignItems: 'center', marginTop: 12 }, buttonPressed: { opacity: 0.7 }, buttonText: { color: '#AD3559', fontSize: 12, fontWeight: '600' } });
