SET NAMES utf8mb4;

INSERT INTO staff_schedule (staff_id, work_date, start_time, end_time, status)
SELECT st.staff_id, DATE_ADD(CURRENT_DATE(), INTERVAL days.day_offset DAY),
       '09:00:00', '18:00:00', 'AVAILABLE'
FROM staff st
JOIN users u ON u.user_id = st.user_id AND u.status = 'ACTIVE'
CROSS JOIN (
  SELECT 0 day_offset UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3
  UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7
  UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11
  UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
  UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
  UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23
  UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27
  UNION ALL SELECT 28 UNION ALL SELECT 29
) days
WHERE NOT EXISTS (
  SELECT 1 FROM staff_schedule existing
  WHERE existing.staff_id = st.staff_id
    AND existing.work_date = DATE_ADD(CURRENT_DATE(), INTERVAL days.day_offset DAY)
);
